version: "3"
services:
  portainer:
    container_name: portainer
    image: "portainer/portainer"
    restart: unless-stopped
    user: "0"
    ports:
      - 9000:9000
    volumes:
      - ./var/run/docker.sock:./var/run/docker.sock
      - ./volumes/portainer/data:/data
  nodered:
    container_name: nodered
    image: "nodered/node-red"
    build: ./services/nodered/.
    restart: unless-stopped
    user: "0"
    ports:
      - 1880:1880
    volumes:
      - ./volumes/nodered/data:/data
  influxdb:
    container_name: influxdb
    image: "influxdb/latest"
    restart: unless-stopped
    user: "0"
    ports:
      - 8086:8086
      - 8083:8083
      - 2003:2003
    env_file:
      - ./services/influxdb/influxdb.env
    volumes:
      - ./volumes/influxdb/data:/var/lib/influxdb
      - ./volumes/influxdb/db:/var/lib/influxdb/backup
  grafana:
    container_name: grafana
    image: "grafana/grafana:6.3.6"
    restart: unless-stopped
    user: "0"
    ports:
      - 3000:3000
    env_file:
      - ./services/grafana/grafana.env
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
      - ./volumes/grafana/log:/var/log/grafana
  mosquitto:
    container_name: mosquitto
    image: "eclipse-mosquitto"
    build: ./services/nodered/.
    restart: unless-stopped
    user: "0"
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./volumes/mosquitto:./mosquitto
      - ./services/mosquitto.mosquitto.conf:/mosquitto/config/mosquitto.conf
