  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    user: "0"
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./volumes/mosquitto/:/mosquitto/
      - ./services/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
