  chronograf:
    container_name: chronograf
    image: chronograf/chronograf:1.7.14
    restart: unless-stopped
    user: "0"
    ports:
      - 8888:8888
    env_file:
      - ./services/chronograf/chronograf.env
    volumes:
      - ./volumes/chronograf/data:/var/lib/chronograf
      - ./volumes/chronograf/log:/var/log/chronograf